### ISSUE TITLE
Status do Processo

### ISSUE THREAD

**Issue by jeffVolt** [daniel777-coder/frontend-challange#15]
Tudo certo por aqui alguma necessidade?
Se precisar de alguma coisa pode me chamar via Whatsapp ou email

**Comment by daniel777-coder** [comment]
Tudo ótimo. Faltam pequenos ajustes. Algumas observações eu ainda quero fazer ao entregar o projeto amanhã. Obrigado!

**Comment by jeffVolt** [comment]
Muito Bom!! Arrebenta.
